version: '3'
services:
  mmis:
    image: "mophos/mmis"
    container_name: "mmis"
    ports:
      - "80:80"
    volumes:
      - /home/mmis/data:/home/mmis/data
      - /home/mmis/mmis-config:/home/mmis/mmis-config
    restart: always
    networks:
      mmis-network:
        ipv4_address: 192.168.1.11
  mysql:
    container_name: "mysql-mmis"
    image: "mysql/mysql-server"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "##Mmis@mmis‚Äù
      MYSQL_ROOT_HOST: "%"
    command: |
      --bind-address=0.0.0.0
      --lower_case_table_names=0
      --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      --skip-name-resolve
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    networks:
      mmis-network:
        ipv4_address: 192.168.1.10

networks:
  mmis-network:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24